# Generated by Django 2.2.3 on 2019-08-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EboardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('eboard_position', models.CharField(max_length=20)),
                ('about_me', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('Summary', models.TextField()),
            ],
        ),
    ]
