# Generated by Django 2.2.3 on 2019-08-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0002_auto_20190802_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_file', models.ImageField(upload_to='pictures')),
                ('on_front_page', models.BooleanField()),
                ('caption', models.TextField(max_length=200)),
                ('alt_text', models.TextField(max_length=200)),
                ('date_taken', models.DateField()),
            ],
        ),
    ]
