# Generated by Django 2.2.3 on 2019-08-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0003_bandpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eboardmember',
            name='eboard_picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkTimeApp.BandPicture'),
        ),
    ]
