# Generated by Django 2.2.3 on 2019-08-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0004_eboardmember_eboard_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyyear',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='historyyear',
            name='year_pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarkTimeApp.BandPicture'),
        ),
    ]
