# Generated by Django 2.2.3 on 2019-08-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0005_auto_20190805_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyyear',
            name='year_pictures',
        ),
        migrations.AddField(
            model_name='bandpicture',
            name='associated_history_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarkTimeApp.HistoryYear'),
        ),
    ]
