# Generated by Django 2.2.3 on 2019-08-07 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpicture',
            name='associated_history_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkTimeApp.HistoryYear'),
        ),
        migrations.AlterField(
            model_name='bandpicture',
            name='date_taken',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
