# Generated by Django 2.2.3 on 2019-08-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0012_auto_20190806_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandpicture',
            name='associated_history_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarkTimeApp.HistoryYear'),
        ),
        migrations.AlterField(
            model_name='eboardmember',
            name='eboard_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarkTimeApp.BandPicture'),
        ),
    ]
