# Generated by Django 2.2.3 on 2019-08-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0013_auto_20190806_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recording',
            name='event',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recording',
            name='performer',
            field=models.CharField(max_length=50),
        ),
    ]
