# Generated by Django 2.2.3 on 2019-08-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0015_recording_songname'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='artist',
            field=models.CharField(default='', max_length=50),
        ),
    ]
