# Generated by Django 2.2.3 on 2019-08-20 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0020_recording_in_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='date_recorded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
