# Generated by Django 2.2.3 on 2019-08-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0021_recording_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyyear',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
