# Generated by Django 2.2.3 on 2019-08-29 20:28

import MarkTimeApp.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0025_remove_eboardmember_is_active_eboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(null=True, upload_to='recordings', validators=[MarkTimeApp.validators.validate_recording_file_extension])),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('song_name', models.CharField(default='', max_length=50)),
                ('artist', models.CharField(default='', max_length=50)),
                ('in_books', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='recording',
        ),
    ]
