# Generated by Django 2.2.3 on 2019-08-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkTimeApp', '0027_auto_20190829_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandpicture',
            options={'ordering': ['date_taken']},
        ),
        migrations.AlterModelOptions(
            name='historyyear',
            options={'ordering': ['year']},
        ),
    ]
